path: contactors
train: train/images
val: valid/images
test: test/images

nc: 1
names: ['Contactors']

roboflow:
  workspace: clement-workspace-uppqr
  project: contactors
  version: 5
  license: CC BY 4.0
  url: https://universe.roboflow.com/clement-workspace-uppqr/contactors/dataset/5